services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  inventory:
    build: ./inventory
    container_name: inventory
    ports:
      - "8000:8000"
    depends_on:
      - redis

  payment:
    build: ./payment
    container_name: payment
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - inventory

  inventory_consumer:
    build: ./inventory
    container_name: inventory_consumer
    command: ["python", "consumer.py"]
    depends_on:
      - redis
    restart: always

  payment_consumer:
    build: ./payment
    container_name: payment_consumer
    command: ["python", "consumer.py"]
    depends_on:
      - redis
    restart: always

  notification:
    build: ./notification
    container_name: notification
    command: ["python", "consumer.py"]
    depends_on:
      - redis
    restart: always